config/routes.rb
Rails.application.routes.draw do
  resources :runners
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount ReplicateRails::Engine => "/replicate/webhook"
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/runner.rb
class Runner < ApplicationRecord
  has_one_attached :document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :set_runner, only: %i[ show edit update destroy ]

  # GET /runners or /runners.json
  def index
    @runners = Runner.all
  end

  # GET /runners/1 or /runners/1.json
  def show
  end

  # GET /runners/new
  def new
    @runner = Runner.new
  end

  # GET /runners/1/edit
  def edit
  end

  # POST /runners or /runners.json
  def create
    @runner = Runner.new(runner_params)

    respond_to do |format|
      if @runner.save
        format.html { redirect_to runner_url(@runner), notice: "Runner was successfully created." }
        format.json { render :show, status: :created, location: @runner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runners/1 or /runners/1.json
  def update
    respond_to do |format|
      if @runner.update(runner_params)
        format.html { redirect_to runner_url(@runner), notice: "Runner was successfully updated." }
        format.json { render :show, status: :ok, location: @runner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runners/1 or /runners/1.json
  def destroy
    @runner.destroy

    respond_to do |format|
      format.html { redirect_to runners_url, notice: "Runner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_runner
      @runner = Runner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def runner_params
      params.fetch(:runner, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReplicTestRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/runners/_form.html.erb
<%= form_with(model: runner) do |form| %>
  <% if runner.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(runner.errors.count, "error") %> prohibited this runner from being saved:</h2>

      <ul>
        <% runner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/runners/_runner.html.erb
<div id="<%= dom_id runner %>">
</div>

app/views/runners/edit.html.erb
<h1>Editing runner</h1>

<%= render "form", runner: @runner %>

<br>

<div>
  <%= link_to "Show this runner", @runner %> |
  <%= link_to "Back to runners", runners_path %>
</div>

app/views/runners/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Runners</h1>

<div id="runners">
  <% @runners.each do |runner| %>
    <%= render runner %>
    <p>
      <%= link_to "Show this runner", runner %>
    </p>
  <% end %>
</div>

<%= link_to "New runner", new_runner_path %>

app/views/runners/new.html.erb
<h1>New runner</h1>

<%= render "form", runner: @runner %>

<br>

<div>
  <%= link_to "Back to runners", runners_path %>
</div>

app/views/runners/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @runner %>

<div>
  <%= link_to "Edit this runner", edit_runner_path(@runner) %> |
  <%= link_to "Back to runners", runners_path %>

  <%= button_to "Destroy this runner", @runner, method: :delete %>
</div>